version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "aws-sam-step-functions-playground"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-13v3pefdyn46p"
s3_prefix = "aws-sam-step-functions-playground"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
