AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  vscode-sam-app

  Sample SAM Template for vscode-sam-app

Resources:
  SimpleStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      Role: !GetAtt StateMachineRole.Arn
      Definition:
        StartAt: Single State
        States:
          Single State:
            Type: Pass
            Result: {"success": true, "item": {"id": 0, "username": "johndoe"}}
            ResultPath: "$.payload"
            Next: TransformPayload
          TransformPayload:
            Type: Pass
            Parameters: {
              "username.$": "$.payload.item.username"
            }
            ResultPath: "$"
            End: true
      Logging:
        Destinations:
          - CloudWatchLogsLogGroup:
              LogGroupArn: !GetAtt StateMachineLogGroup.Arn
        IncludeExecutionData: true
        Level: ALL            
      # Policies:
      #   - CloudWatchPutMetricPolicy: {}
      Events:
        EBRule:
          Type: EventBridgeRule
          Properties:
            Pattern:
              source:
                - "com.mycompany.myapp"
        ApiEvent:
          Type: Api
          Properties:
            Path: /start
            Method: get

  StateMachineRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service: states.amazonaws.com
          Action: sts:AssumeRole
      Policies:
        - PolicyName: LoggingPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
            - Effect: Allow
              Action:
              - logs:CreateLogDelivery
              - logs:GetLogDelivery
              - logs:UpdateLogDelivery
              - logs:DeleteLogDelivery
              - logs:ListLogDeliveries
              - logs:PutResourcePolicy
              - logs:DescribeResourcePolicies
              - logs:DescribeLogGroups
              Resource: '*'
        - PolicyName: CloudWatchMetricPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
            - Effect: Allow
              Action:
              - cloudwatch:PutMetricData
              Resource: '*'

  StateMachineLogGroup:
    Type: AWS::Logs::LogGroup


Outputs:
  ApiURL:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/start/"

  
